parameters:
  - name: "temperature_sensor"
    protocol: modbus
    register: 40001
    min: 0
    max: 50
    interval: 10

  - name: vibration_sensor
    protocol: mqtt
    topic: iot/sensors
    min: 0.2
    max: 1.5
    interval: 5

  - name: motor_speed
    protocol: modbus
    register: 40010
    min: 50 
    max: 70
    interval: 2

email:
    username: "your_email@gmail.com"
    password: "your_password"
    smtp_server: "smtp.gmail.com"
    port: 587
    recipients:
      - "receiver@example.com"

MQTT:
    Broker: "broker.hivemq.com"
    Port: 1883

